volumes:
  mongo:

services:
  app:
    build: .
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    restart: on-failure:3
